services:
  - type: web
    name: ca-compliance-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: compliance-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: compliance-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: '["*"]'  # Update this with your frontend URL when ready
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

databases:
  - name: compliance-db
    databaseName: compliance_db
    user: compliance_user

  - name: compliance-redis
    type: redis
